using System.Collections.Generic;
using System.Linq;

namespace SightoHear.Services.Lyrics
{
    public class LyricsData
    {
        public List<LyricsLine> LyricsLines { get; set; } = [];
        public string? LanguageCode { get; set; }
        public bool AutoGenerated { get; set; } = false;
        public string WrappedOriginalText => string.Join("\r\n", LyricsLines.Select(line => line.PrimaryText));
        public bool IsWordByWord => LyricsLines.Any(x => x.IsPrimaryHasRealSyllableInfo);

        public LyricsData()
        {
        }

        public LyricsData(List<LyricsLine> lyricsLines)
        {
            LyricsLines = lyricsLines;
        }
    }
}
